algoritmo "Funções Aritméticas"
// Função :
// Autor :
// Data : 18/06/2022
// Seção de Declarações 
var
   a: real
inicio
       //a <- abs(-50) valor absoluto
       //a<- exp(9, 5)exponenciando 9 a 5° potencia
       //a<- raizq(81)raiz quadrada
       //a<- int(raizq(90))
       //a<- grauprad(90)conversão de graus para radianos
       a<- sen(grauprad(90))// conventendo 90 para radianos e informando em seno que só aceita valores em radianos
       escreva(a)
fimalgoritmo
