algoritmo "testeEscopo"
// Função :
// Autor :
// Data : 03/07/2022
// Seção de Declarações 
var
   n1, n2: inteiro//n1,n2 variaveis Globais
procedimento rotina(a, b: inteiro)
var
   x, y: inteiro //a, b, x, y: variaveis locais
inicio
      x <- a
      y <- b
      escreva(n1, n2, a, b, x, y)
fimprocedimento
inicio
      n1 <- 5
      n2 <- 3
      rotina(n1, n2)
      escreva(n1, n2, a, b, x, y)
fimalgoritmo
