algoritmo "ex003"

var
    nome: caractere
    sal: real
inicio
      escreval("3) Crie um programa que leia o nome e o salário de um funcionário, mostrando no")
      escreval("final uma mensagem.")
      escreval()
      escreva("Nome do funcionário: ")
      leia(nome)
      escreval()
      escreva("Salário(reais.centavos): ")
      leia(sal)
      escreval()
      escreva("O funcionário ", nome, " tem um salário de R$", sal," em Junho.")
      escreval()
fimalgoritmo
