algoritmo "ex007"

var
     n, d, t:real
inicio
      escreval("7) Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a sua")
      escreval("terça parte.")
      escreval()
      escreva("Digite um número: ")
      leia(n)
      escreval()
      d <- n * 2
      escreval("O dobro de",n," é",d)
      t <- n / 3
      escreval()
      escreval("A terça parte de",n," é", t)
fimalgoritmo
