algoritmo "Faça um programa que leia as duas notas de um aluno em uma matéria e mostre na tela a sua média na disciplina"
// Função :
// Autor :
// Data : 18/06/2022
// Seção de Declarações 
var
   n: caractere
   n1, n2, m: real
inicio
      escreva("Aluno digite o seu nome: ")
      leia(n)
      escreva("Nota 1: ")
      leia(n1)
      escreva("Nota 2: ")
      leia(n2)
      m <- (n1 + n2)/2
      escreva("A média entre",n1," e",n2, " é igual a",m )
fimalgoritmo
