algoritmo "ex006"

var
     n, a, s: inteiro
inicio
      escreval("6) Faça um programa que leia um número inteiro e mostre o seu antecessor e seu")
      escreval("sucessor.")
      escreval()
      escreva("Digite um número: ")
      leia(n)
      escreval()
      a <- n - 1
      escreval("O antecessor de",n," é", a)
      escreval()
      s <- n + 1
      escreval("O sucessor de",n," é", s)
fimalgoritmo
