algoritmo "ex003"

var
    nome: caractere
    sal: real
inicio
      escreval("3) Crie um programa que leia o nome e o salário de um funcionário, mostrando")
      escreval("no final uma mensagem.")
      escreva("Nome do funcionário: ")
      leia(nome)
      escreva("Salário(reais.centavos): ")
      leia(sal)
      escreva("O funcionário ", nome, " tem um salário de R$", sal," em Junho.")
fimalgoritmo
