algoritmo "ex003"

var
    nome: caractere
    sal: real
inicio
      escreval("3) Crie um programa que leia o nome e o sal√°rio de um funcion√°rio, mostrando no")
      escreval("final uma mensagem.")
      escreval()
      escreva("Nome do funcion·rio: ")
      leia(nome)
      escreval()
      escreva("Sal·rio(reais.centavos): ")
      leia(sal)
      escreval()
      escreva("O funcion·rio ", nome, " tem um sal·rio de R$", sal," em Junho.")
      escreval()
fimalgoritmo
