algoritmo "ex004"
var
   n1, n2, s: inteiro
inicio
      escreval("4) Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório")
      escreval("entre eles.")
      escreval()
      escreva("Digite um número: ")
      leia(n1)
      escreval()
      escreva("Digite outro número: ")
      leia(n2)
      escreval()
      s <- n1 + n2
      escreval(" A soma entre",n1," e",n2," é igual a",s,".")
fimalgoritmo
