algoritmo " ex020"
var
      n1, n2 : inteiro
inicio
      escrevaL("20) Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou")
      escreval("ÍMPAR.")
      escreval()
      escreva("Digite um número inteiro: ")
      leia(n1)
      escreval()
      Se (n1 % 2 = 0) entao
         escreval("O número",n1," é PAR!")
      senao
           escreval("O número",n1, " é IMPAR!")
       fimse
fimalgoritmo
