algoritmo " Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou ÍMPAR. "
// Função :
// Autor :
// Data : 25/06/2022
// Seção de Declarações 
var
      n1, n2 : inteiro
inicio
       escreva("Digite um número inteiro: ")
       leia(n1)
       Se (n1 % 2 = 0) entao
          escreva("O número",n1," é PAR!")
       senao
            escreva("O número",n1, " é IMPAR!")
       fimse
fimalgoritmo
