algoritmo "Crie um programa que mostre na tela a seguinte contagem, usando a estrutura “faça enquanto” 0 3 6 9 12 15 18 21 24 27 30 Acabou!"
// Função :
// Autor :
// Data : 03/07/2022
// Seção de Declarações 
var
   contador: inteiro
inicio
      contador <- 0
      repita
          escreva(contador)
          contador <- contador + 3
      ate(contador > 30)
      escreva(" Acabou!")
fimalgoritmo
