algoritmo "ex067"
var
   contador, n:inteiro
inicio
      escreval("67) Faça um programa usando a estrutura “para” que leia um número inteiro")
      escreval("positivo e mostre na tela uma contagem de 0 até o valor digitado:")
      escreval
      escreva("Deseja contar até que valor: ")
      leia(n)
      escreval()
      para contador <- 0 ate n faca
           escreval(contador,",")
      fimpara
      escreval(" FIM!")
fimalgoritmo
