algoritmo "ex072"
var
   v: vetor[0..9] de inteiro
   c: inteiro
inicio
      escreval("72) Crie um programa que preencha automaticamente (usando lógica, não apenas")
      escreval("atribuindo diretamente) um vetor numérico com 10 posições, conforme abaixo:")
      escreval()
      para c <- 5 ate 50 passo 5 faca
           escreva("[ ",c,"]")
      fimpara
       escreval()
      para c <- 0 ate 9 faca
           escreva("  ",c,"  ")
      fimpara
      escreval()
fimalgoritmo
