algoritmo "ex3"
// Função :
// Autor :
// Data : 18/06/2022
// Seção de Declarações 
var
    nome: caractere
    sal: real
inicio
      escreval("3) Crie um programa que leia o nome e o salário de um funcionário, mostrando/no final uma mensagem.")
      escreva("Nome do funcionário: ")
      leia(nome)
      escreva("Salário(reais.centavos): ")
      leia(sal)
      escreva("O funcionário ", nome, " tem um salário de R$", sal," em Junho.")
fimalgoritmo
